name: todoapp_backend
description: Dart replacement for the Flask backend used by the Todoapp project.
version: 0.0.1
environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqlite3: ^1.2.0
  dotenv: ^4.2.0
  uuid: ^3.0.7
